[package]
name = "sample-scsi"
version = "0.10.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]
edition = "2024"

[dependencies]
clap = ">=0.6.6"
separator = "0.4.1"
number_prefix = "0.4.0"
hdd = { path = ".." }
